In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import image

# ULAB Physics & Astronomy: Python Module VII

## Question 1: A Stack Full of Arrays [15 Points]

You are given two 2D arrays ``a`` and ``b``. For example,

```
>>> a
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
       
>>> b
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

### 1a
Implement a function ``vstacked`` which returns a new array with the values of ``a`` and ``b`` vertically stacked. For example,

```
>>> vstacked(a,b)
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

Hint: you can use ``numpy.vstack`` or ``numpy.concatenate`` and specify axis.

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


def vstacked(a,b):
    return ...

In [ ]:
print(vstacked(a,b))

### 1b

Implement a function ``hstacked`` which returns parameters ``a`` and ``b`` horizontally stacked. For example,

```
>>> hstacked(a,b)
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [ ]:
def hstacked(a,b):
    return ...

In [ ]:
hstacked(a, b)

## Question 2 : The Gray Oski [15 Points]

With Valentine's Day coming up next week, it is only appropriate to admire the image of Oski below. 

In [ ]:
img = image.imread('oski.jpeg')
plt.imshow(img)
plt.show()

``img`` is a numpy array with shape,
```
>>> img.shape
(1160, 1800, 3)
```

This indicates that the images is 1160x1800 pixels large with 3 color channels (R, G, B). The data is stored as a 1160 row by 1800 column matrix where each element of the matrix is an array containing the color values of each pixel.

Suppose we believe this image would look better in grayscale. To convert a colored image to grayscale, we must create a new array of size ``(1160, 1800)`` and combine the 3 color values into a single grayscale value.

Using eq. 7 of this [reference](grayscale_conversion.pdf), create a new image ``gray`` that is the grayscale version of ``img``. Use a color map to project the image ``gray`` to a gray color map.


In [ ]:
gray = ...
#This is just a grayscale value. Doesn't really map to gray unless you use a color map

In [ ]:
plt.imshow(..., ...)
plt.show()

Now, flip your image across the x-axis

In [ ]:
gray_flipped=...
plt.imshow(...,...)
plt.show()

Flip it across the y-axis now

In [ ]:
gray_flipped=...
plt.imshow(...,...)
plt.show()

## Question 3: A Star is Born [20 Points]

The European Space Agency’s Gaia space mission has provided an unprecedented catalog of over 1 Billion star positions and brightnesses. A subset of those have been collected into the Gaia Catalog of Nearby stars, containing about 300,000 stars within 100 pc. 

You will use a subset of data from the Gaia Catalog of Nearby Stars and make a four panel plot that shows a HR Diagram in each panel. An HR diagram is similar to a color-magnitude diagram. The panels will be distinct in that each uses a different filter in order to eliminate 25-75% of the data points. Each panel should be related to stellar populations or the importance of the quality of data. Write a caption for each panel

<b> Step 1</b> We will import a library called pandas as pd

In [ ]:
import pandas as pd

<b> Step 2</b> We will use pandas to read a csv file. This has been done for you. Run the cell below

In [ ]:
df = pd.read_csv('GaiaSource_2112514745830880640_2112747296837846528.csv')
df

```df``` above stands for data frame. It embodies the file we just read. From the ```df``` above, we want to select 3 color filters for our HR Diagram. We do this by mentioning the column name being selected. For instance, if we want to select the ```bp_rp``` filter (The Blue-Red Filter), we can run the following command:

In [ ]:
blue_red=df['bp_rp']

<b> Step 3:</b> Use the example above to call 2 columns: ```bp_g``` (Blue-Green Filter) and ```g_rp``` (Green-Red Filter)

In [ ]:
blue_green = df[...]
green_red = df[...]

<b> Step 4: </b> Select the luminosity column from ```df```. The luminosity column has the following name: ```lum_val```

In [ ]:
luminosity = ...

<b> Step 5: </b> Use subplots to draw the three-panel HR Diagrams. 

In your 0th axes, plot (use a scatter plot) the ```blue_red``` v/s ```lum_val```. Give your points an orange color.  


In your 1st axes, plot (use a scatter plot) the ```blue_green``` v/s ```lum_val```. Give your points a blue color.  


In your 2nd axes, plot (use a scatter plot) the ```green_red``` v/s ```lum_val```. Give your points a green color.  

For all three diagrams, set s (the size of each data point in your scatter plot) to 1 and set your yscale to ```log```.

In [ ]:
fig, ax = plt.subplots(1, 3, figsize=(20,10)) # Gives you your figure, 3 axes and sets the figure size to 20x10
#This step sets x limits for your 0th, 1st and 2nd graph
ax[0].set_xlim(0,4)
ax[1].set_xlim(0,4)
ax[2].set_xlim(0,4)

#Use the space below to complete the task
...
plt.show()

## Submission

Check to make sure that you have answered all questions. Run all the cells so that all output is visible. Finally, export this notebook as a PDF (File/Download As/PDF via LaTeX (.pdf)) and submit to bCourses.

<b>References:</b> 

Questions inspired by work by Selva Prabhakaran and Vasu Gupta.

Images: Yi Zhu, 2018

Last Updated: Feb 2023